gui:
  # stuff relating to the UI
  scrollHeight: 4 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - red
      - reverse
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default # set to `default` to have no background colour
      - underline
      - bold
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
  mouseEvents: true
